Capex/Models/Request.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Capex.Models
{
    public class Request
    {
        [Display(Name = "№ Заявки")]
        public int RequestID { get; set; }

        [Display(Name = "Пользователь")]
        public virtual User User { get; set; }

        [Display(Name = "Дата создания")]
        public DateTime CreationDate { get; set; }

        [Required(ErrorMessage = "Требуется поле Описание")]
        [Display(Name = "Описание")]
        public string Description { get; set; }

        [Display(Name = "Стоимость")]
        [DisplayFormat(DataFormatString = "{0:F2}", ApplyFormatInEditMode = true)]
        public decimal Value { get; set; }

        [Display(Name = "Валюта")]
        public Currency Currency { get; set; }

        [Display(Name = "Детальное описание и обоснование")]
        public string LongDescription { get; set; }

        [Display(Name = "Комментарий по обработке заявки")]
        public string CommentRequest { get; set; }

        [Display(Name = "Состояние заявки")]
        public RequestState State { get; set; }
    }

    public enum Currency
    {
        [Display(Name = "UAH")]
        UAH,

        [Display(Name = "EUR")]
        EUR,

        [Display(Name = "USD")]
        USD,

        [Display(Name = "RUR")]
        RUR
    }

    public enum RequestState
    {
        [Display(Name = "Создана")]
        Created,

        [Display(Name = "Отменена")]
        Cancelled,

        [Display(Name = "Подтверждена менеджером")]
        ApprovedByManager,

        [Display(Name = "Отправлено на согласование")]
        SentToMedicover,

        [Display(Name = " Подтверждена CFO Medicover")]
        ApprovedByMedicover,

        [Display(Name = "Завершена")]
        Finalized,

        [Display(Name = "На доработке")]
        ClarificationNeeded,

        [Display(Name = "Все")]
        All
    }

    public enum Unit
    {
        [Display(Name = "Украина")]
        Украина,

        [Display(Name = "Россия")]
        Россия,

        [Display(Name = "Беларусь")]
        Беларусь,

        [Display(Name = "Все")]
        All
    }
}

Capex/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Configuration;
using System.Net.Mail;
using System.Reflection;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;
using System.DirectoryServices;
using System.DirectoryServices.AccountManagement;

namespace Capex.Models
{
    public class RequestsController : Controller
    {
        private CapexContext db = new CapexContext();

        // GET: Requests
        public ActionResult Index(bool filter=false)
        {
            if (filter)
            {
                return Index((RequestState?)Session["State"], (Unit?)Session["Unit"], (DateTime?)Session["StartCreationDate"], (DateTime?)Session["EndCreationDate"]);
            }
            SetUnitAndState();
            // проверяем есть ли такой пользователь в  бд таблице USER
            if(((from c in db.Users where c.UserID == User.Identity.Name select c.FullName).FirstOrDefault()) == null)
            {
                return RedirectToAction("Error");
            }

            UserRole role = (from c in db.Users
                             where c.UserID == User.Identity.Name
                             select c.Role).FirstOrDefault();

            // получаем заявки текущего пользователя
            var requests = (from Rq in db.Requests
                            where Rq.User.UserID == User.Identity.Name
                            select Rq).Union
                           (from R in db.Requests
                            where (from U in db.Users where U.ManagerID == User.Identity.Name select U.UserID).Contains(R.User.UserID)
                            select R);

            if (role == Capex.Models.UserRole.ViewAll)
            {
                ViewBag.Access = false;
                // получаем All заявки
                requests = (from R in db.Requests select R);
                return View(requests.ToList());
            }
            else
            {
                ViewBag.Access = true;
            }

            if (role == UserRole.FinancialManager || role == UserRole.CFOMedicove)
            {
                var requests_ = (from Rq in db.Requests select Rq);
                return View(requests_.ToList());
            }

            bool? view_All_Request_for_User =
               db.Users.Where(x => x.UserID == User.Identity.Name).Select(x => x.ViewAll).FirstOrDefault();
            if (view_All_Request_for_User == true)
            {
                // получаем заявки текущего пользователя
                ViewBag.All_Request = (from Rq in db.Requests
                                       where Rq.User.UserID == User.Identity.Name
                                       select Rq.RequestID).Union
                               (from R in db.Requests
                                where (from U in db.Users where U.ManagerID == User.Identity.Name select U.UserID).Contains(R.User.UserID)
                                select R.RequestID).ToList();

                requests = (from Rq in db.Requests select Rq);
            }
            return View(requests.ToList());
        }

        [HttpPost]
        public ActionResult Index(RequestState? State, Unit? Unit, DateTime? StartCreationDate, DateTime? EndCreationDate)
        {
            SetUnitAndState();
            InitializationFilterVariable(State, Unit, StartCreationDate, EndCreationDate);
            UserRole role = (from c in db.Users
                             where c.UserID == User.Identity.Name
                             select c.Role).FirstOrDefault();
            if (role == Capex.Models.UserRole.ViewAll)
            {
                ViewBag.Access = false;
            }
            else
            {
                ViewBag.Access = true;
            }
            if (role == UserRole.FinancialManager || role == UserRole.CFOMedicove || role == UserRole.ViewAll)
            {
                IEnumerable<Request> requests = (from Rq in db.Requests select Rq).ToList();
                List<Request> filteredList = GetRequests(State, Unit, StartCreationDate, EndCreationDate, requests);
                return View(filteredList.ToList());
            }
            else
            {
                bool? view_All_Request_for_User =
                 db.Users.Where(x => x.UserID == User.Identity.Name).Select(x => x.ViewAll).FirstOrDefault();
                if (view_All_Request_for_User == true)
                {
                    // получаем заявки текущего пользователя
                    ViewBag.All_Request = (from Rq in db.Requests
                                           where Rq.User.UserID == User.Identity.Name
                                           select Rq.RequestID).Union
                                   (from R in db.Requests
                                    where (from U in db.Users where U.ManagerID == User.Identity.Name select U.UserID).Contains(R.User.UserID)
                                    select R.RequestID).ToList();
                    IEnumerable<Request> requests = db.Requests.ToList();
                    List<Request> filteredList = GetRequests(State, Unit, StartCreationDate, EndCreationDate, requests);
                    return View(filteredList.ToList());
                }
                else
                {
                    // получить список заявок user, manager
                    IEnumerable<Request> requests = (from Rq in db.Requests
                                                     where Rq.User.UserID == User.Identity.Name
                                                     select Rq).Union
                                                     (from R in db.Requests
                                                      where (from U in db.Users where U.ManagerID == User.Identity.Name select U.UserID).Contains(R.User.UserID)
                                                      select R).ToList();
                    List<Request> filteredList = GetRequests(State, Unit, StartCreationDate, EndCreationDate, requests);
                    return View(filteredList.ToList());
                }
            }                         
        }

        private void InitializationFilterVariable(RequestState? State, Unit? Unit, DateTime? StartCreationDate,DateTime? EndCreationDate)
        {
            Session["State"] = State;
            Session["Unit"] = Unit;
            Session["StartCreationDate"] = StartCreationDate;
            Session["EndCreationDate"] = EndCreationDate;
        }

        [HttpPost]
        public ActionResult ShowAll()
        {
            return RedirectToAction("Index");
        }

        // GET: Requests/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Request request = db.Requests.Find(id);
            if (request == null)
            {
                return HttpNotFound();
            }
            return View(request);
        }

        public ActionResult Details_ViewAllRole(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Request request = db.Requests.Find(id);
            if (request == null)
            {
                return HttpNotFound();
            }
            return View(request);
        }

        // GET: Requests/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Requests/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RequestID,CreationDate,Description,Value,Currency,LongDescription,CommentRequest,State,User_Id")] Request request)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // некоторые значения дефолтные
                    request.User = (from c in db.Users
                                    where c.UserID == User.Identity.Name
                                    select c).FirstOrDefault();
                    request.CreationDate = DateTime.Now;
                    // получаем роль текущего пользователя
                    UserRole role = (from c in db.Users
                                     where c.UserID == User.Identity.Name
                                     select c.Role).FirstOrDefault();
                    if(role == UserRole.User)
                    {
                        request.State = RequestState.Created; // "Created"
                    }
                    else
                    if(role == UserRole.Manager)
                    {
                        request.State = RequestState.ApprovedByManager;
                    }
                    else
                    if (role == UserRole.CFOMedicove)
                    {
                        request.State = RequestState.ApprovedByMedicover;
                    }
                    else
                    {
                        request.State = RequestState.Created; // "Created"
                    }                        

                    request.Value = decimal.Round(request.Value, 2); // округлим до 2 знака после запятой
                    db.Requests.Add(request);
                    db.SaveChanges();
                    EmailNotification(request.User, request.RequestID, request.Description);
                    return RedirectToAction("Index");
                }
            }
           catch(Exception ex)

Capex/Views/Requests/Create.cshtml
@model Capex.Models.Request

@{
    ViewBag.Title = "Создать";
}

<h2>Создать заявку</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group" style="display:none;"> 
            @Html.LabelFor(model => model.UserID, "Пользователь", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group" style="display:none;">
            @Html.LabelFor(model => model.CreationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreationDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })            
            @Html.Label("*", htmlAttributes: new { @style = "text-align:left; margin-left:-20px; color:red; width:0px;", @class = "control-label col-md-1" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.Label("*", htmlAttributes: new { @style = "text-align:left; margin-left:-20px; color:red; width:0px;", @class = "control-label col-md-1" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.Label("Округление до сотых", htmlAttributes: new { @style = "color:green; font-style:italic;" })<br/>
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>
        

        <div class="form-group">
            @Html.LabelFor(model => model.Currency, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.Label("*", htmlAttributes: new { @style = "text-align:left; margin-left:-20px; color:red; width:0px;", @class = "control-label col-md-1" })
            <div class="col-md-9">
                @Html.EnumDropDownListFor(model => model.Currency, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Currency, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LongDescription, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.LongDescription, new {cols = 40, @rows = 5, @style = "margin-left:10px;"})
                @Html.ValidationMessageFor(model => model.LongDescription, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CommentRequest, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.CommentRequest, new { cols = 40, @rows = 5, @style = "margin-left:10px;" })
                @Html.ValidationMessageFor(model => model.CommentRequest, "", new { @class = "text-danger" })
            </div>
        </div>

        

        @*<div class="form-group" style="display:none;">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CreateState", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-3 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Index")
</div>

Capex/Views/Requests/Delete.cshtml
@model Capex.Models.Request

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Request</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.ManagerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.ManagerID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Currency)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Currency)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LongDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LongDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Capex/Views/Requests/Details.cshtml
@model Capex.Models.Request

@{
    ViewBag.Title = "Details";
}

<h2 style="text-align:center;">Details</h2>

<div>
    <h4 style="text-align:center;">Request</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RequestID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestID)
        </dd>
        @*<dt>
            @Html.DisplayNameFor(model => model.UserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserID)
        </dd>*@
        <dt>
            @Html.DisplayNameFor(model => model.User.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User.ManagerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.ManagerID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Currency)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Currency)
        </dd>         
        <dt>
            @Html.DisplayNameFor(model => model.LongDescription)
        </dt>

        <dd>
            @Html.TextAreaFor(model => model.LongDescription, 5, 100, htmlAttributes: new {style = "width: 100%; max-width: 100%;", @readonly = true})
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CommentRequest)
        </dt>
        <dd>
            @Html.TextAreaFor(model => model.CommentRequest, 5, 100, htmlAttributes: new { style = "width: 100%; max-width: 100%;", @readonly = true })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>
    </dl>   
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.RequestID }) |
    @Html.ActionLink("Вернуться к списку", "Index", new {filter = true})
</p>

Capex/Views/Requests/Index.cshtml
@model IEnumerable<Capex.Models.Request>

@{
    ViewBag.Title = "Capex";
}

<h2 style="text-align:center;">Список заявок</h2>
<h4 style="text-align:center;">
    @if (ViewBag.Access == true)
    {
        @Html.ActionLink("Создать", "Create", null, htmlAttributes: new { @style = "color:#5CB85C; text-decoration:none", @class= "glyphicon glyphicon-pencil" })
    }
 </h4>

@using (Html.BeginForm())
{
    <div class="filter">
        <div class="row" style="padding-top:18px; padding-left:5px; font-style:italic; padding-bottom:10px;">
            <div class="col-md-2">
                Состояние:
                @Html.DropDownList("State", null, htmlAttributes: new { @style = "width:180px; height:26px;" })               
            </div>
            <div class="col-md-2">
                Подразделение:
                @Html.DropDownList("Unit", null, htmlAttributes: new { @style = "width:180px; height:26px;" })
            </div>
            <div class="col-md-2">
                Дата от:
                @Html.TextBox("StartCreationDate", "{0:yyyy-MM-dd}", new { @style = "width:180px; height:26px;", type = "date" })
            </div>
            <div class="col-md-2">
                Дата до:
                @Html.TextBox("EndCreationDate", "{0:yyyy-MM-dd}", new { @style = "width:180px; height:26px;", type = "date" })
            </div> 
            <div class="col-md-2" style="text-align:left; padding-top:12px;">
                @*All
                <br/>
                @Html.CheckBox("AllRequesrts", new { @style = "width:40px; height:26px;" })*@
                <button name="action" value="filter" class="btn btn-success" style="width:170px; height:35px; border-radius:10px;">Фильтр <i class="glyphicon glyphicon-filter" style="padding-left: 10px;"></i></button>
            </div>    
           </div>        
      </div>       
}

@using (Html.BeginForm("ShowAll", "Requests"))
{
    <div class="col-md-2" style="text-align:right; padding-top:12px; padding-right:30px; float:right; margin-top:-57px;">
        <button name="allRequesrts" value="allRequesrts" class="btn btn-primary" style="width:170px; height:35px; border-radius:10px;">Показать все<i class="glyphicon glyphicon-list-alt" style="padding-left: 10px;"></i></button>
    </div>
}

<table class="table table-condensed table-striped" id="TableResults">
    <thead style="background-color: LightSkyBlue; text-align: center;">
        <tr>
            <th>
                @*@Html.ActionLink("№ Заявки", "Index", new { SortRequest = ViewBag.NameSortParm })*@
                @Html.DisplayNameFor(model => model.RequestID)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.UserID)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.User.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User.Unit)
            </th>
            <th>
                @*@Html.ActionLink("Дата создания", "Index", new { SortRequest = ViewBag.DateSortParm })*@
                @Html.DisplayNameFor(model => model.CreationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @*@Html.ActionLink("Стоимость", "Index", new { SortRequest = ViewBag.ValueSortParm })*@
                @Html.DisplayNameFor(model => model.Value)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Currency)
            </th>
            @*<th>
                        @Html.DisplayNameFor(model => model.LongDescription)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th class="no-sort">
                @Html.DisplayName("Комментарий")
            </th>
            <th class="no-sort">
            </th>
           </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RequestID)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.UserID)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.User.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.User.Unit)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreationDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Value)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Currency)
                </td>
                @*<td>
                            @Html.DisplayFor(modelItem => item.LongDescription)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CommentRequest)
                </td>
                <td>
                    @if (ViewBag.Access == true)
                    {
                        if (ViewBag.All_Request != null)
                        {
                            if (ViewBag.All_Request.Contains(item.RequestID))
                            {
                                @Html.Label(" | ")
                                @Html.ActionLink("Редактировать", "Edit", new {id = item.RequestID})
                                @Html.Label(" | ")
                                @Html.ActionLink("Просмотр", "Details", new {id = item.RequestID})
                            }
                        }
                        else
                        {
                            @Html.Label(" | ")
                            @Html.ActionLink("Редактировать", "Edit", new {id = item.RequestID})
                            @Html.Label(" | ")
                            @Html.ActionLink("Просмотр", "Details", new {id = item.RequestID})
                        }
                    }
                    else
                    {
                        @Html.ActionLink("Просмотр", "Details_ViewAllRole", new { id = item.RequestID })
                    }
                    @*@Html.ActionLink("Delete", "Delete", new { id=item.RequestID })*@
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    $(document).ready(function() {
        var table = $('#TableResults').DataTable(
           {
               "order": [[0, "desc"]],
               "columnDefs": [{
                   "targets": 'no-sort',
                   "orderable": false
               }]
           });
    });
</script>